version: "3"

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgresql-data:/var/lib/postgresql/data

  app:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python3 manage.py collectstatic --no-input; python3 manage.py migrate; uvicorn mysite.asgi:application --port 8000 --host 0.0.0.0'
    volumes:
      - static:/app/staticfiles
    depends_on:
      - db
    restart: on-failure

  api:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn mysite.asgi:fastapp --port 8000 --host 0.0.0.0'
    depends_on:
      - db
      - wsify
    restart: on-failure
    
  # pgadmin:
  #   image: dpage/pgadmin4
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=a@a.com
  #     - PGADMIN_DEFAULT_PASSWORD=n0passw0rd
  #   depends_on:
  #     - db

  wsify:
    build: ./wsify
    command: wsify -webhook=http://api:8000/check/ -debug

  nginx:
    command: nginx -g "daemon off;"
    depends_on:
      - api
      - app
      - wsify
    image: nginx:alpine
    restart: on-failure
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static:/var/www/app/static
      - ./frontend:/var/www/app/frontend
    ports:
      - "127.0.0.1:8000:8000"
  
  worker_runner:
    build:
      context: .
      dockerfile: worker_runner/Dockerfile
    depends_on:
      - api
    
volumes:
  postgresql-data:
  static:
